

== Ḥadīth References

=== Deeds coming to an end

The Messenger (peace and blessings of Allaah be upon him) said: “When a man dies, his good deeds come to an end except three: ongoing charity, beneficial knowledge and a righteous child who will pray for him.” — Muslim, no. 3084.

=== Waqf Basis

It is narrated that ʿUmar (may Allah be pleased with him) said: “O Messenger of Allah, I have got wealth from Khaybar and I have nothing that is more precious to me than that. What do you command me to do with it?” He said, “If you wish, you can put it aside and give in charity from it (from what it produces), but the original property should not be sold, given away or inherited.” So ʿUmar gave it in charity to the poor and to relatives, used it to set slaves free, gave it for the sake of Allaah, helped wayfarers and honoured his guests. — Al-Bukhārī and Muslim.

=== Charity to Family
[[dirham-hadith]]

Abū Hurayrah (May Allah be pleased with him) narrated that the Prophet (Peace be upon him) commanded to give sadaqah. A man said: O Messenger of Allah, I have a _dīnār_. He (Peace be upon him) said: Spend it on yourself. He again said: I have another. He (Peace be upon him) said: Spend it on your children. He again said: I have another. He (Peace be upon him) said: Spend it on your wife. He again said: I have another. He (Peace be upon him) said: Spend it on your servant. He finally said: I have another. He (Peace be upon him) replied: You know best (what to do with it). — Abū Dāwūd, no. 1691.

=== Waṣiyyah before Prophet Muḥammad
[[wasiyyah-nuh]]
ʿAbdullāh ibn ʿAmr said, “We were sitting with the Messenger of Allah, may Allah bless him and grant him peace, when a bedouin man wearing a robe with a border approached him until he stood before the Messenger of Allah, may Allah bless him and grant him peace. He said, ‘Your companion has debased every horseman and elevates every shepherd.’ The Prophet, may Allah bless him and grant him peace, took hold of the folds of his robe and said, ‘I see that you are wearing the clothes of someone who is without intelligence.’ Then he went on, ‘When the *Prophet Nūḥ*, may Allah bless him and grant him peace, told his son, “I will give you some instructions. I command you two things and I forbid you two things. I command you to say, ‘There is no god but Allah.’ If the seven heavens and the seven earths were a dark ring, they would be cut by ‘There is no god but Allah’ and ‘Glory be to Allah and by His praise.’ It is the prayer of every thing and by it everything has its provision. And I forbid you to associate others with and Allah and to be proud.”’” — Imam al-Bukhārī in _al-Adab al-Mufrad_ (no. 548)

=== Will Limit
[[will-limit]]

It was narrated that Saʿd ibn Abī Waqqāṣ said: “The Messenger of Allah visited me when I was sick, and said: ‘Have you made a will?’ I said: ‘Yes.’ He said: ‘How much?’ I said: ‘For all my wealth to be given in the cause of Allah.’ He said: ‘What have you left for your children?’ I said: ‘They are rich (independent of means).’ He said: ‘Bequeath one-tenth.’ And we kept discussing it until he said: ‘Bequeath *one-third*, and one-third is much or large.’” — Al-Nasāʾī, no. 3631.

=== Governance of Orphans' Wealth

[[abu-dharr-leadership]]

Abū Dharr narrated that the Messenger of of Allah (Peace be upon him) said, “Abū Dharr, I find that you are weak and I like for you what I like for myself. Do not rule over (even) two persons and do not manage the property of an orphan.” — Muslim, no. 1826.
