= Fiqh for Economists III Notes
Khalid Hussain <mohammad.khalid.hussain@gmail.com>
:imagesdir: assets/images
:toc: left
:icons: font
:stem:

== General Information

.[.arabic]#حقائق#
. [.arabic]#حقيقة لغوية#
. [.arabic]#حقيقة شرعية#
. [.arabic]#حقيقة عرفية#

== Waqf

[.lead]
Def.: A permanent dedication of the corpus of the valuable property by a Muslim to the ownership of Allah for religious, charitable, and pious purposes.

* Waqf property cannot be sold, mortgaged, donated, or alienated, even by inheritance.
* Only the income produced by Waqf property can be consumed. The Waqf property itself cannot be consumed.
* Charity to family members is better than charity to strangers. Please see _ḥadīth_ of <<dirham-hadith, Abū Hurayrah>>.

.Pillars of Waqf
. Founder [.arabic]#واقف#
. Waqf property [.arabic]#موقوف#
. Beneficiaries [.arabic]#موقوف عليه#
. Expression [.arabic]#صيغة#

NOTE: The conditions of the [.arabic]#واقف# must be respected unless they are invalid Sharīʿah wise.

== Al-Waṣiyyah

[.lead]
Def: A gift that is given after the death of the [.arabic]#موصي#.

Waṣiyyah existed in the nations before the Prophet Muhammad (Peace be upon him). See hadith of <<wasiyyah-nuh, ʿAbdullāh ibn ʿAmr>>.

NOTE: _Kafārah_ exists even for actions that are considered _muʿāmalāt_. Example: _al-Ẓihār_.

. It is a gift from Allah the Mighty and Exalted.
. It cannot be given to an heir who will inherit. The distinction is important in English as there can be heirs who will not inherit anything.
. The limit of _waṣiyyah_ is stem:[1/3] of the [.arabic]#مال#. Evidence for this is the _ḥadīth_ of <<will-limit, Saʿd ibn Abī Waqqās>>

[IMPORTANT]
.Waṣiyyah that is greater than one-third
====
If *directed to a stranger*, will be given if all the heirs AGREE, otherwise, it will be *reduced to the maximum*, i.e. one-third, and then given.

If *directed to an heir* (who will inherit), it will be given if all the other heirs AGREE, otherwise it will be *invalidated*.
====

== Wardship

It is not recommended to become a guardian of orphans' wealth. See the ḥadīth of <<abu-dharr-leadership, Abū Dharr>>.

The benefit of the child comes first. Preservation of religion is the greatest benefit.

A person cannot buy from his ward since there is a clash of interests.

According to (some) Ḥanafīs, _Zakāt_ must be paid on all wealth irrespective of who it belongs to. Be they a ward, an insane person, etc...

=== Custody
. Who has right to custody after divorce (EXPAND ON THIS SECTION)

== Inheritance

[.lead]
[.arabic]#حق مالي ثبت لمستحق بعد موت من كان له سلة بينهما#

.NOTE: I don't know the name of this list
. [.arabic]#مؤن التجهيز#
.. Anything the deceased needs until burial. Examples: perfume, _ghusl_, transport, _kafn_, grave (if it needs to be bought), and wages for gravediggers.
. [.arabic]#الديول المتعلقة بالتركة عينها#
.. If Zayd lent money to ʿAmr with the latter's car as guarantee, then that car is part of the estate in the case of ʿAmr's death.
. [.arabic]#الديول المطلقة في ذمة الميت، (لله أولادمي)#
. [.arabic]#وصية الميت#
. [.arabic]#نصيب ورثة الميت#

Memorize the following ayāt:

. Ayāt 11, 12, 176 of [.arabic]#النساء#
. Ayāh 6 of [.arabic]#الأحزاب#

The Islamic system of inheritance is just and distributes rights according to the Lord's absolute wisdom. Whatever the portion may be for any of the inheritors, it is justice.

[quote]
____
The only way to beat the Muslims is not by the sword but rather by taking the hijāb from the woman and placing it over the Quran.
____

Ustadh Ibrahim has written an article along the lines of “Law of Inheritance from the Book of Allah.” In it, he extracts almost all of the rulings of Inheritance from the Quran without depending on ḥadīth narrations. I have yet to download this and read it.

IMPORTANT: The important aspect of a foetus with respect to inheritance is that it exists in the womb at the time of the death of the deceased. We are not concerned with whether it is born dead or alive. (Clarification: If born dead, who takes his share?)

.[.arabic]#أسباب الإرث#
. [.arabic]#النكاح#
. [.arabic]#النسب#
. [.arabic]#ولاء#

=== Deprivers

Assuming at least one of the [.arabic]#أسباب# is present, only the following may deprive one of inheritance.

.Inheritance Deprivers
. _Kufr_
. Murder
. Slavery

The murder that is intended when discussing the deprivation of inheritance is the murder of the deceased by one or more of his inheriting heirs.

==== Murder

.Types of Murder
. [.arabic]#العَمْدُ# Intentional
. [.arabic]#شِبْهُ العَمْدِ# Looks intentional (Ex: A child dies due to beating by a stick.)
. [.arabic]#الخَطَأُ# Unintentional

According to the Shāfiʿīs, murder of any of these kinds deprives a person from inheritance irrespective of his position to the murder (witness, judge, witness of behavior to a witness, etc...) except for TWO people:

. A _ḥadīth_ narrator (al-Rāwī)
. A Muftī who passes judgement of death (This requires clarification)

==== Slavery

.Types of Slaves
. [.arabic]#القِنُّ#
. [.arabic]#المُبَعَضُ#
.. A partial slave. Example: Two people buy a slave and then one of them manumits his respective part.
.. According to the Ḥanbalīs, such a slave may inherit through his free part.
. [.arabic]#المُكَاتَب#
.. Needs to pay a certain amount to his master in order to manumit himself.
.. Involves some issues with _zakāt_.
. [.arabic]#المُدَبَّرُ#
.. Becomes free after the death of the master due to an agreement by the latter.
. [.arabic]#أم ولد#
.. Consists of two issues.
... Can she be sold?
... Does she become free when you die? Yes. The slave is part of the estate of the master and as such will be inherited. Since children cannot enslave their parents and vice versa, the mother will be manumitted. This answer assumes that at least one child will inherit her.


[NOTE]
.Marrying a slave-girl
====
Marrying a slave-girl is not allowed except in TWO cases:

. If he cannot afford to marry a free woman.
. He fears with certainty that he will commit _zinā_ if he doesn't marry the slave-girl.

// Insert ḥadīth of parent and children that cannot be turned into slaves.
====

=== Heirs

.Types of Inheriting Heirs
. Males (15 of them)
. Females (10 of them)

.Males
. Son [.arabic]#الإبن#
. Son's Son [.arabic]#ابن الإبن (وإن نزل)#
. Father [.arabic]#الأب#
. Father's Father [.arabic]#أب الأب (وأن علا بمحض الذكور)#
. Full Brother [.arabic]#الأخ من الأبوين#
. Consanguine Brother [.arabic]#الأخ من الأب#
. Uterine Brother [.arabic]#الأخ من الأم#
. Full Brother's Son [.arabic]#ابن الأخ من الأبوين (وإن نزل)#
. Consanguine Brother's Son [.arabic]#ابن الأخ من الأب (وإن نزل)#
. Father's Full Brother [.arabic]#العم من الأبوين (وإن علا)#
. Fathers' Consanguine Brother [.arabic]#العم من الأب (وإن علا)#
. Father's Full Brother's Son [.arabic]#ابن العم من الأبوين (وإن نزل)#
. Father's Consanguine Brother's Son [.arabic]#ابن العم من الأب (وإن نزل)#
. Husband [.arabic]#الزوج#
. [.arabic]#المعتِق#

.Females
. Daughter [.arabic]#البنت#
. Son's Daughter [.arabic]#بنت الأبن (وإن نزل)#
. Mother [.arabic]#الأم#
. Mother's Mother [.arabic]#أم الأم (وإن علت بمحض الإناث)#
. Father's Mother [.arabic]#أم الأب (وإن علت بمحض الإناث) أو أم الأب (وإن علا بمحض الذكور)#
. Full Sister [.arabic]#الأخت من الأبوين#
. Consanguine Sister [.arabic]#الأخت من الأب#
. Uterine Sister [.arabic]#الأخت من الأم#
. Wife [.arabic]#الزوجة#
. [.arabic]#المعتقة#

NOTE: Any (grand)mother that is connected to someone who inherits, will inherit.

.Categories
. [.arabic]#الأصول# - F, FF, M, MM, FM
. [.arabic]#الفروع# - S, D, SS, SD
. [.arabic]#هواشي# - Everyone else

.Types of portions for inheritors
. _Taʾsīb_ — without fixed portion
.. All the males (15) are included here *except* the husband (-1), uterine brother (-1). Al-Muʿtiqah (+1) is also here. *Total of 14*.
. _Farḍ_ — with fixed portion
.. All the females (10) are included here *except* al-Muʿtiqah (-1). The husband (+1) and uterine brother(+1) are also included. *Total of 11*.

=== Al-Furūḍ al-Muqaddarah

There are 6. They are stem:[\frac{1}{2}], stem:[\frac{1}{4}], stem:[\frac{1}{6}], stem:[\frac{1}{8}], stem:[\frac{1}{3}] and stem:[\frac{2}{3}].

=== Uṣūl al-Masāʾil

There are two divisions:

1. SEVEN Agreed upon bases: stem:[2, 3, 4, 6, 8, 12, 24].
2. TWO Disagreed upon bases: stem:[18, 36].

=== Al-Furūḍ's Distribution

==== 1/2

. Daughter
.. On condition that she's the only child.
. Son's Daughter
.. On condition that she's the only child and only grandchild.
. Full Sister
.. No male _ʿAṣl_ is alive.
.. No _Farʿ_ is alive.
.. No other full sibling.
. Consanguine Sister
.. No male _ʿAṣl_ is alive.
.. No _Farʿ_ is alive.
.. No full siblings.
.. No other consanguine sibling.
. Husband
.. No _Farʿ_ is alive.

==== 1/4

. Husband
. Wife

==== 1/8

. Wife
.. {Existence of _Farʿ al-Wārith_}

==== 2/3

. Everyone under 1/2 except the husband.
.. No other male siblings.
.. Other female (full?/consanguine?) siblings should be present
.. Other conditions from 1/2 apply.

==== 1/3

. Mother
.. No child or grandchild ([.arabic]#وإن نزل#).
.. There shouldn't be a group of more than one sibling (any kind: consanguine, full, or uterine).
.. The inheritance case should not be from the ([.arabic]#الغرويين#).
. Uterine siblings (weakest entities in inheritance matters)
.. No male _ʿAṣl_ is alive.
.. No child or grandchild ([.arabic]#وإن نزل#).
.. They have to be more than one.
.. The principle of one male to two females ratio doesn't apply here.

==== 1/6

. Father
.. Only when there is a child or grandchild ([.arabic]#وإن نزل#).
. Mother
.. When there is [.arabic]#فرع الوارث#..
.. If there is a group of more than one sibling.
. Father's Father
.. Father is not alive.
.. No [.arabic]#فرع الوارث#. exist.
.. The inheritance case should not be the case of [.arabic]#الجد والإخوة#.
. Any Grandmother
.. Mother is not alive.
. Son's Daughter
.. No male child or male grandchild ([.arabic]#وإن نزل#).
.. The deceased is survived by only one daughter.
. Consanguine Sister
.. No male _ʿAṣl_.
.. No [.arabic]#فرع الوارث#. exist.
.. No (consanguine or full) male sibling.
.. Only one full sister exists.
. Uterine Sibling
.. No male _ʿAṣl_.
.. No [.arabic]#فرع الوارث#. exist.
.. He/She has to be the only sibling.

=== Al-Taʿṣīb (ʿAṣabah)

.Types of ʿAṣabah
. ʿAṣabah bi al-Nafs [.arabic]#عصبة بالنفس#
.. Every male except husband and uterine brother.
. ʿAṣabah bi al-Ghayr [.arabic]#عصبة بالغير#
.. They are ʿaṣīb due to another person and they inherit with them (the same portion is assigned to both).
. ʿAṣabah maʿ al-Ghayr [.arabic]#عصبة مع غير#
.. They are ʿaṣīb due to another person and they inherit due to them (different portions are assigned to them).

include::hadith_references.adoc[]
include::questions-and-answers.adoc[]
include::_glossary.adoc[]
